// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type NewWeatherStation struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
	Type string `json:"type,omitempty" yaml:"type,omitempty" xml:"type,omitempty"`
}

func (v *NewWeatherStation) Validate() error {

	// ToDo: Improve validation of MaxLength

	if len(v.Name) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "name")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Type) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "type")
	}

	return nil
}
