// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type WeatherUpdate struct {
	Title       string `json:"title,omitempty" yaml:"title,omitempty" xml:"title,omitempty"`
	Description string `json:"description,omitempty" yaml:"description,omitempty" xml:"description,omitempty"`
	Timestamp   string `json:"timestamp,omitempty" yaml:"timestamp,omitempty" xml:"timestamp,omitempty"`
}

func (v *WeatherUpdate) Validate() error {

	// ToDo: Improve validation of MaxLength

	if len(v.Title) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "title")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Description) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "description")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Timestamp) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "timestamp")
	}

	return nil
}
