// Don't edit this file, as it is generated by dredger
package entities

import (
	"fmt"
)

type WeatherStation struct {
	Type        string        `json:"type,omitempty" yaml:"type,omitempty" xml:"type,omitempty"`
	Id          string        `json:"id,omitempty" yaml:"id,omitempty" xml:"id,omitempty"`
	LastReading WeatherUpdate `json:"lastReading,omitempty" yaml:"lastReading,omitempty" xml:"lastReading,omitempty"`
	Name        string        `json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
}

func (v *WeatherStation) Validate() error {

	// ToDo: Improve validation of MaxLength

	if len(v.Type) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "type")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Id) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "id")
	}

	// ToDo: Improve validation of MaxLength

	if len(v.Name) > 9223372036854775807 {
		return fmt.Errorf("string '%s' is too long", "name")
	}

	return nil
}
